name: Nightly Docker Build

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build . -t $IMAGE_NAME/nextchat:${{ env.TIMESTAMP }}

      - name: Tag Docker image for Docker Hub
        run: |
          docker tag $IMAGE_NAME/nextchat:${{ env.TIMESTAMP }} ${{ secrets.DOCKER_USERNAME }}/nextchat:${{ env.TIMESTAMP }}
          docker tag $IMAGE_NAME/nextchat:${{ env.TIMESTAMP }} ${{ secrets.DOCKER_USERNAME }}/nextchat:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nextchat:${{ env.TIMESTAMP }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nextchat:latest

