name: Nightly Docker Build

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: yangappid
          password: Aa@123456

      - name: Get current timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          IMAGE_NAME=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build . -t $IMAGE_NAME/nextchat:${{ env.TIMESTAMP }}

      - name: Tag Docker image for Docker Hub
        run: |
          docker tag $IMAGE_NAME/nextchat:${{ env.TIMESTAMP }} ${{ secrets.DOCKER_USERNAME }}/nextchat-nightly:v${{ env.TIMESTAMP }}
          docker tag $IMAGE_NAME/nextchat:${{ env.TIMESTAMP }} ${{ secrets.DOCKER_USERNAME }}/nextchat-nightly:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nextchat-nightly:v${{ env.TIMESTAMP }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nextchat-nightly:latest

      - name: Save Docker image as .tar file
        run: |
          IMAGE_FILE=./nextchat-docker-v${{ env.TIMESTAMP }}.tar
          docker save $IMAGE_NAME/nextchat:${{ env.TIMESTAMP }} -o $IMAGE_FILE
          echo "Docker image saved as $IMAGE_FILE"
          echo "ASSET_PATH=$IMAGE_FILE" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: nextchatweb-nightly-${{ env.TIMESTAMP }}
          name: Nightly Build v${{ env.TIMESTAMP }}
          body: |
            Changes in this release:
            - Nightly build release for version v${{ env.TIMESTAMP }}
          draft: false
          prerelease: false

      - name: Upload Docker image to GitHub Release as asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ASSET_PATH }}
          asset_name: nextchat-docker-v${{ env.TIMESTAMP }}.tar
          asset_content_type: application/x-tar
